version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    env_file: ./db/.env
    environment:
      - TZ=America/Bogota
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.10
    env_file: ./db/.env
    environment:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER='"Bienvenido a pgAdmin"'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on: [postgres]
    restart: unless-stopped

  api_gestion:
    build: { context: ./backend/gestion, target: prod }
    container_name: api_gestion
    env_file: ./backend/gestion/.env
    depends_on: [postgres]
    restart: unless-stopped

  api_control:
    build: { context: ./backend/control, target: prod }
    container_name: api_control
    env_file: ./backend/control/.env
    depends_on: [postgres]
    restart: unless-stopped

  front_gestion:
    build: { context: ./frontend/gestion, target: prod }
    container_name: front_gestion
    env_file: ./frontend/gestion/.env_prod
    restart: unless-stopped

  proxy:
    build: { context: ./nginx }
    container_name: proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [postgres, pgadmin, api_gestion, api_control, front_gestion]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on: [proxy]
    entrypoint: sh
    command: -c "if [ -n '-d api.control.cremososmateo.com -d api.gestion.cremososmateo.com -d gestion.cremososmateo.com -d pgadmin.cremososmateo.com' ]; then certbot certonly -n --keep-until-expiring --webroot -w /var/www/certbot -d api.control.cremososmateo.com -d api.gestion.cremososmateo.com -d gestion.cremososmateo.com -d pgadmin.cremososmateo.com --email \"andrew19f@gmail.com\" --agree-tos --no-eff-email ; fi; trap exit TERM; while :; do certbot renew -n --webroot -w /var/www/certbot --quiet || true; sleep 12h; done"
    restart: unless-stopped

volumes:
  pg_data:
  pgadmin_data:
