version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: ingMaster_postgres_dev
    env_file: ./db/.env
    environment:
      - TZ=America/Bogota
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: ingMaster_pgadmin_dev
    env_file: ./db/.env
    environment:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER='"Bienvenido a pgAdmin"'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - '5050:80'
    depends_on: [postgres]
    restart: unless-stopped

  api_controlpersonal:
    build: { context: ./backend/controlpersonal, target: dev }
    container_name: api_controlpersonal
    env_file: ./backend/controlpersonal/.env
    volumes:
      - ./backend/controlpersonal/app:/code
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on: [postgres]
    ports:
      - '8000:80'
    restart: unless-stopped

  api_gestion:
    build: { context: ./backend/gestion, target: dev }
    container_name: api_gestion
    env_file: ./backend/gestion/.env
    volumes:
      - ./backend/gestion/app:/code
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on: [postgres]
    ports:
      - '8001:80'
    restart: unless-stopped

  front_gestion:
    build: { context: ./frontend/gestion, target: dev }
    container_name: front_gestion
    volumes:
      - ./frontend/gestion/app:/app
      - front_gestion_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./frontend/gestion/.env
    command: npm run dev -- --host 0.0.0.0
    ports:
      - '5173:5173'
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    container_name: ingMaster_proxy_dev
    ports: [ '80:80' ]
    volumes:
      - ./nginx_dev/conf.d:/etc/nginx/conf.d:ro
      - ./nginx_dev/proxy_params.conf:/etc/nginx/proxy_params.conf:ro
    depends_on: [postgres, pgadmin, api_controlpersonal, api_gestion, front_gestion]
    restart: unless-stopped

volumes:
  front_gestion_node_modules:
  pg_data:
  pgadmin_data:
